spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rest-admin?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 600000
      max-life-time: 1800000


server:
  port: 6666

#分组
springdoc:
  group-configs:
    - { group: 'rest-cms', packages-to-scan: 'cn.soboys.springbootjpa.controller' }

rest-api:
  json:
    number-form: '.00' # 浮点数格式化  ,000,00 不足补零。,###.## 不会补零 （四舍五入）
    date-form: yyyy-MM-dd HH:mm:ss.SSS  #时间格式化  timestamp 时间戳
    null-able:  # 对空返回处理
      has-null-able: false # 默认不处理   original 类型代表单个不做任何处理
      number-type: number # 处理number 空返回 "0"
      array-type: array # 处理集合空返回 []
      double-type: double # 处理double 类型空返回 "0.00"
#mybatis-flex:
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
