spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rest-admin?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 600000
      max-life-time: 1800000

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update # 控制是否可以基于程序中Entity的定义自动创建或者修改DB中表结构
    show-sql: true #控制是否打印运行时的SQL语句与参数信息
    database-platform: org.hibernate.dialect.MySQLDialect  #数据库方言
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true  # https://stackoverflow.com/questions/46259878/org-hibernate-lazyinitializationexception-failed-to-lazily-initialize-a-collect
        #加载获取异常问题
        session_factory:
          statement_inspector: cn.soboys.simplestjpa.interceptor.TenantInterceptor


server:
  port: 9999

#分组
springdoc:
  group-configs:
    - { group: 'rest-cms', packages-to-scan: 'cn.soboys.springbootjpa.controller' }

rest-api:
  json:
    number-form: '.00' # 浮点数格式化  ,000,00 不足补零。,###.## 不会补零 （四舍五入）
    date-form: yyyy-MM-dd HH:mm:ss.SSS  #时间格式化  timestamp 时间戳
    null-able:  # 对空返回处理
      has-null-able: false # 默认不处理   original 类型代表单个不做任何处理
      number-type: number # 处理number 空返回 "0"
      array-type: array # 处理集合空返回 []
      double-type: double # 处理double 类型空返回 "0.00"

# 需进行租户配置
tenant:
  tables:
    - cms_category
  tenant-id-column: id
  enable-tenant: true

